### ISSUE TITLE
Confusing results for `genpointings`

### ISSUE THREAD

**Issue by ziotom78** [lspestrip/Stripeline.jl#8]
The behavior of `genpointings` is confusing when the caller uses UTC times in the parameter list. As it is now, `genpointings` accepts the following time-related inputs:

- The number of samples to generate (length of the `timerange_s` parameter)
- The sampling frequency (derived from the spacing in `timerange_s` samples)
- The start and end times

This set of parameters is redundant: one might derive the end time from the number of samples and the sampling frequency. Consider the following example:

```julia
d1, psi1 = genpointings([0, 0, 1], 
                    0:0.1:1, # Just 11 samples, with a sampling frequency of 10 Hz
                    DateTime(2019, 01, 01, 0, 0, 0), 
                    DateTime(2022, 04, 13, 21, 10, 10),  # 3 years after start
                    latitude_deg=10.0,
                    longitude_deg=20.0,
                    height_m = 1000) do time_s
           (0.0, deg2rad(20.0), timetorotang(time_s, 1))
       end

d2, psi2 = genpointings([0, 0, 1], 
                    0:0.1:1, # Same number of samples as above (11) and same sampling freq.
                    DateTime(2019, 01, 01, 0, 0, 0), 
                    DateTime(2022, 01, 13, 21, 10, 10),  # Just two weeks after start
                    latitude_deg=10.0,
                    longitude_deg=20.0,
                    height_m = 1000) do time_s
           (0.0, deg2rad(20.0), timetorotang(time_s, 1))
       end
```

The start time, the sampling frequency and the number of samples are the same in the two calls. One might thus expect the two calls to return the same directions. Yet this does not happen:
```
julia> d1
11×2 Array{Float64,2}:
 0.165338  2.45028 
 0.168944  3.81077 
 0.17017   5.17096 
 0.172777  0.247507
 0.178315  1.60732 
 0.183707  2.96762 
 0.186145  4.32798 
 0.187337  5.6877  
 0.19103   0.763828
 0.197232  2.12351 
 0.201767  3.48379 

julia> d2
11×2 Array{Float64,2}:
 0.165338  2.45028
 0.167971  4.43896
 0.169262  0.14338
 0.175654  2.13099
 0.179272  4.11957
 0.180024  6.10732
 0.185865  1.81145
 0.190459  3.79981
 0.190973  5.78769
 0.196025  1.49167
 0.201477  3.47975
```

This means that the parameter `t_stop` plays a role. From a look at the code, it seems that the function always generates a set of uniformly-spaced Julian dates between `t_start` and `t_stop`. This might however not be always the case: the parameter `timerange_s` might contain a set of times with no regular sampling frequency, as in this example:
```julia
d1, psi1 = genpointings([0, 0, 1], 
                    [3600.0, 86400.0], # Sample pointings after one hour and after one day
                    DateTime(2019, 01, 01, 0, 0, 0), 
                    DateTime(2022, 04, 13, 21, 10, 10)) do time_s
           (0.0, deg2rad(20.0), timetorotang(time_s, 1))
       end
```

Perhaps the best option would be to make `t_stop` disappear.

**Comment by fincardona** [comment]
Done
